In [1]:
ls = ['abrar', 'Ibrahim']
ls2 = 'St' + ls

TypeError: can only concatenate str (not "list") to str

In [20]:
import numpy as np
import re

In [15]:
t = np.zeros((2,3,4), dtype = 'float32')

In [17]:
print(t[0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
text = "Texmex is a messy? I don't know !!!"

In [29]:
re.findall(r"[^\s\w]", text)

['?', "'", '!', '!', '!']

In [32]:
re.findall(r"[\w]+[^\s\w]", text)

['messy?', "don'"]